<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>login</title>
        
    </head>
    <body>
        <h1>logueate</h1>
        <form action="lf2/usuario/" method="post" >
            <input type="email" name="email_usuario" placeholder="Email Usuario"/> 
            <input type="password" name="pass_usuario" placeholder="Password" />

         <input type="submit" value="enviar"/>
        </form>
    </body>
</html>
